version: "3.6"
services:
  postgres:
    image: bitnami/postgresql:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8082:8080"
    restart: always
    networks:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: admin12345
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

networks:
  postgres:
    driver: bridge
